# Generated by Django 2.0.8 on 2018-09-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federalagency',
            options={'verbose_name_plural': 'Federal Agencies'},
        ),
        migrations.AlterModelOptions(
            name='stateagency',
            options={'verbose_name_plural': 'State Agencies'},
        ),
        migrations.AlterModelOptions(
            name='subrecipient',
            options={'verbose_name_plural': 'Sub-Recipients'},
        ),
        migrations.AlterField(
            model_name='federalagency',
            name='cgac_code',
            field=models.CharField(max_length=3, verbose_name='CGAC Code'),
        ),
        migrations.AlterField(
            model_name='federalagency',
            name='federal_hierarchy_level',
            field=models.CharField(choices=[('department', 'Department/Ind. Agency'), ('sub_tier', 'Sub-tier')], max_length=10, verbose_name='Federal Hierarchy Level'),
        ),
        migrations.AlterField(
            model_name='federalagency',
            name='org_name',
            field=models.CharField(max_length=128, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='stateagency',
            name='org_name',
            field=models.CharField(max_length=128, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='subrecipient',
            name='org_name',
            field=models.CharField(max_length=128, verbose_name='Organization Name'),
        ),
    ]
