# Generated by Django 2.0.8 on 2018-09-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_auto_20180924_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalagency',
            name='org_url',
            field=models.URLField(blank=True, default='', verbose_name='Main Organization URL'),
        ),
        migrations.AddField(
            model_name='stateagency',
            name='duns_number',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='DUNS Number'),
        ),
        migrations.AddField(
            model_name='stateagency',
            name='org_url',
            field=models.URLField(blank=True, default='', verbose_name='Main Organization URL'),
        ),
        migrations.AddField(
            model_name='subrecipient',
            name='duns_number',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='DUNS Number'),
        ),
        migrations.AddField(
            model_name='subrecipient',
            name='org_url',
            field=models.URLField(blank=True, default='', verbose_name='Main Organization URL'),
        ),
        migrations.AlterField(
            model_name='federalagency',
            name='federal_hierarchy_level',
            field=models.CharField(choices=[('department', 'Department/Ind. Agency'), ('sub_tier', 'Sub-tier')], default='department', max_length=10, verbose_name='Federal Hierarchy Level'),
        ),
        migrations.AlterField(
            model_name='stateagency',
            name='agency_code',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='RIFANS Agency Code'),
        ),
    ]
